### ISSUE TITLE
Combining multiple plugins into one custom plugin

### ISSUE THREAD

**Issue by paaljoachim** [DevinWalker/custom-functionality-plugin-example#1]
Hey

I find the setup very useful especially the tutorial from your web page:
http://wordimpress.com/building-first-custom-functionality-plugin/
To get me into coding.

Suggestions on what to add into a custom function plugin.
- Customizing the login screen. What about customizing the timeout screen as well?
  Adding a sidebar widget to add a login section? Adding social login?
- Adding a widget to the Dashboard area. Including an example on adding a background image through CSS (I am not sure where or how to place the specific CSS for it) Customizing the full Dashboard area.
- A broader add/remove modify sidebar items. Taking it further then the tutorial. With additional CSS examples on customizing the look of the WordPress backend.
  Forcing the user to use one color profile.
- How to add shortcodes. Then showing examples of adding a background box, containing a color, a shadow, curved corners etc. Featured posts. Columns. Background color or image per page.
- How to add a backend custom panel. To turn on or off specific features.
- Breadcrumbs.
- Widgets as shortcodes into a page or post content area.
- Social menu bar.
- Drag and drop similar to this plugin:
  http://wordpress.org/plugins/intuitive-custom-post-order/
- Protecting open e-mail addresses:
  http://wordpress.org/plugins/email-address-encoder/
- Adding an image avatar. Instead of a gravatar.
- Directly jumping between posts and pages.
  Similar to http://wordpress.org/plugins/orbisius-quick-nav/
- Better control of menus. Show hide based on role etc.
- Authorbox.
- Styles - Styles to change various colors etc.
  http://wordpress.org/plugins/styles/

**Comment by DevinWalker** [comment]
Thank you for the detailed suggestions. I'm glad you found this plugin useful. Here are a few thoughts I have:

_Customizing the login screen. What about customizing the timeout screen as well?_
- I like the idea of customizing the timeout as well; will put this on the dev path

_Adding a sidebar widget to add a login section? Adding social login?_
- not sure about this; tabled

_Adding a widget to the Dashboard area. Including an example on adding a background image through CSS (I am not sure where or how to place the specific CSS for it) Customizing the full Dashboard area._
- CSS territory; I don't really want to add a bg image to the dashboard. A simple widget is fine for this example.

A broader add/remove modify sidebar items. Taking it further then the tutorial. _With additional CSS examples on customizing the look of the WordPress backend._
- Perhaps I will include example code to create your own admin page for settings, etc.

_Forcing the user to use one color profile._
- Yes!

_How to add shortcodes. Then showing examples of adding a background box, containing a color, a shadow, curved corners etc. Featured posts. Columns. Background color or image per page._
- Simple shortcode example... I like!

_How to add a backend custom panel. To turn on or off specific features._
- Yes!

_Breadcrumbs._
- Nah

_Widgets as shortcodes into a page or post content area._
- Maybe 

_Social menu bar._
- Plugin territory 

_Drag and drop similar to this plugin:
http://wordpress.org/plugins/intuitive-custom-post-order/_
- plugin territory 

_Protecting open e-mail addresses:
http://wordpress.org/plugins/email-address-encoder/_
- plugin territory 

_Adding an image avatar. Instead of a gravatar._
- Maybe; tabled

_Directly jumping between posts and pages.
Similar to http://wordpress.org/plugins/orbisius-quick-nav/_
- For these items where there is an existing plugin I believe I will include TGM Plugin Activation class that requires certain plugins be active. http://tgmpluginactivation.com/

_Better control of menus. Show hide based on role etc._
- Will add an example

_Authorbox._
- Probably theme territory here unless I misunderstand what an authorbox is

_Styles - Styles to change various colors etc.
http://wordpress.org/plugins/styles/_
- req. w/ TGM

Again thanks for the updates! I'm going to be working some of your suggestions into the code. Stay tuned in!

**Comment by paaljoachim** [comment]
Awesome!

Dashboard. I am just thinking of showing an extended code example on how to adjust the background color of the full area as well as other widgets. To get an idea how how it can be done.
Authorbox is meant as the author profile box. When to include it as in pages/posts (or even specific pages/posts) and link to the CSS style used.

I am thinking of at the end of each section there could be of "how to extend" how to tips. To give the users extra tips in extending the examples seen.

The important part is how to activate custom functions, and how to call in the CSS for the specific function. Each person will need to figure out the CSS used and modify it, but when the base is in place each user can easily configure from there.

A few more:
Turning off commenting on all pages.
A quick code for no entry page titles. Yes it can easily be done in the CSS but including it into the Custom Functions will take care of that aspect as well in creating new pages.
A form.
It seems there are a lot of CSS that will be repeated for each site. I am thinking that some of this can then be added in connection with the Custom Functions file. Creating a kind of template aspect for many areas of a site.

I am looking forward to the various examples!

**Comment by DevinWalker** [comment]
I just pushed out a number of updates yesterday. It includes a sample CPT, taxonomy and metabox/fields integration. Thanks for all the great ideas!

**Comment by DevinWalker** [comment]
Paal - thank you for the comments. I'm going to close this issue since it's not really an 'issue' but I will use it as reference when adding new features.

**Comment by paaljoachim** [comment]
I look forward to additional updates and an update to the blog entry http://wordimpress.com/building-first-custom-functionality-plugin/

Have a great day!

**Comment by paaljoachim** [comment]
I change certain things inside the Settings area for every site.
- Turn off the Organize my uploads into month- and year-based folders.
- Permalinks use Post name or custom category and post name.
- Date format, time format, Week starts on.

It would be nice with a section on changing the defaults inside the Settings area. So it becomes automated because of the custom functionality plugin. As in just add the plugin and the various settings change depending on the changes one has created.
